install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
data("diamonds")
View(diamonds)
head(diamonds)
str(diamonds)
glimpse(diamonds)
colnames(diamonds)
#Cleaning data
rename(diamonds, carat_new = carat)
rename(diamonds, carat_new = carat, cut_new = cut)
summarize(diamonds, mean_carat = mean(carat))
library(tidyverse)
mutate(diamonds,carat_2=carat*100)
#Visualizing data
ggplot(data = diamonds, aes(x = carat, y = price)) +  geom_point()
ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +  geom_point()
ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +  geom_point() + facet_wrap(~cut)
#creates a different plot for each type of cut. `ggplot2` makes it easy to do this with the `facet_wrap()` function
