library(palmerpenguins)
data("penguins")
library(ggplot2)
View(penguins)
ggplot(data=penguins)+geom_point(mapping = aes(x=flipper_length_mm,y=body_mass_g,color=species,shape=species))
ggplot(data=penguins)+geom_boxplot(mapping = aes(x=flipper_length_mm,y=body_mass_g))
ggplot(data=penguins)+geom_smooth(mapping = aes(x=flipper_length_mm,y=body_mass_g),method = lm)
ggplot(data=penguins)+geom_rug(mapping = aes(x=flipper_length_mm,y=body_mass_g,color=species))
ggplot(data=penguins)+geom_tile(mapping = aes(x=flipper_length_mm,y=body_mass_g,color=species))
